### ISSUE TITLE
You can’t open the application “ReverseImageSearch.app” because it may be damaged or incomplete.

### ISSUE THREAD

**Issue by yourmomdatestedcruz** [yimingliu/reverse-image-search-safari#25] opened 2023-01-14 22:50 UTC
Hey,

I wanted to update to v1.3.6 to get Google Lens functionality, but it looks like I'm having an issue launching the app to add it to Safari.

I tried running sudo xattr -cr; and sudo spctl --master-disable as well, but no luck. Looks like the last step is deleting a bunch of files from my computer, but just wanted to make sure there wasn't another step I could try before doing that.

System specs:
MacOS Monterey 12.4
MacBook Pro with touchbar (2018) - intel CPU

Let me know if you need more details to see what is going on!

**Comment by yimingliu** [comment] 2023-01-14 23:41
I can't reproduce this issue on my macOS Ventura installations. Which of course doesn't mean there is no issue, just that I don't have your specific setup.  Worth noting that the app is signed with my paid Apple Developer ID and notarized by Apple, so it should not require additional security overrides besides allowing "Identified Developers".  However, it is true that this is the first time I notarized the app with the new XCode in Ventura.

A few questions to start with:

- To be sure, Gatekeeper is configured to allow identified developers in addition to app store, yes?
- You mentioned this was an upgrade. Did any previous version work for you?  All previous releases are available for download [in the Releases page.](https://github.com/yimingliu/reverse-image-search-safari/releases).  
   - Is the previous version still on disk?
- If you happen to have access to another macOS installation, can you test the app on another machine?
- If you happen to have codesign available, what is the output of `codesign -vvv --verify insert_path_to_app_here` e.g. `codesign -vvv --verify /Applications/ReverseImageSearch.app` in Terminal?

I will need a few days to obtain access to a Monterey installation that doesn't have my Developer ID installed already, in order to test this scenario more fully.

**Comment by yourmomdatestedcruz** [comment] 2023-01-15 13:46
It seems like 1.3.5 also has the same issue, so I'm inclined to think it's my machine.

I can't test with another machine, and don't have codesign available; but no rush - probably me trying to be smarter than I should.

**Comment by yimingliu** [comment] 2023-01-17 06:29
With a macOS Monterey machine that I borrowed, which never had my developer key, I still cannot reproduce this problem.

Other generic troubleshooting procedures:
- if you create a new user on your machine, log in as this test user, and try to run the app, does that work?
- what was the last version that worked for you? is there a precise version at which it stops working?  Or does any version other than what you already have fail?
- there some procedures online about deleting some files to reset the state of certain apps -- I honestly don't know if that will work, as I have never run into this issue myself.

As a final test, I've recompiled ReverseImageSearch.app, and included both a notarized and unnotarized version. Safari will not permanently install an unnotarized extension, unfortunately.

- give the recompiled version a try, just in case it's something weird going on with the previous release
- if that doesn't work still, try to see if you can _open_ the unnotarized version by overriding gatekeeper.  Again, Safari will not load the extension, but you could try to see if the containing app even opens on your machine

[ReverseImageSearch.zip](https://github.com/yimingliu/reverse-image-search-safari/files/10431937/RIS.zip)

Sorry I don't really have any thing more substantial to suggest at this time.

**Comment by yourmomdatestedcruz** [comment] 2023-01-25 11:00
Wooo alright - it's working now, and here's what I had to do, which was VERY strange?

1. Downloaded v1.3.6
2. Extracted Zip archive contents
3. Moved application to 'Applications' folder - icon still had a blocked logo overlayed.
4. Opened the package contents.
5. Renamed the .app file contained, and moved that to the 'Applications' folder.
6. Tried opening that it worked but did not appear in the Safari extensions list.
7. ran `sudo xattr -c [path_to_file]` 
8. Tried to open it again, it did appear in the extensions list
9. Now works as expected.

**Comment by yimingliu** [comment] 2023-03-28 23:29
I'm glad that worked -- will close this issue now and refer anyone else who might have the problem to this issue.

**Closed as completed by yimingliu** 2023-03-28 23:29 UTC
Labels: bug, workaround
