### ISSUE TITLE
This seems broken?

### ISSUE THREAD

**Issue by gingerbeardman** [yimingliu/reverse-image-search-safari#2] opened 2019-08-04 17:23 UTC
I just upgraded to Mojave, and this seems broken sometimes.

- context menus sometimes do not appear
- when they do appear, if i choose them the image search does not open
- after choosing the menu item, they will not appear again

will try to get some debug information

**Comment by yimingliu** [comment] 2019-08-04 17:40
I am personally using this extension on Mojave and have not had issues, though admittedly I only use this occasionally.

Are the issues reproducible on a specific site or sites?  Or everywhere?  I assume this is also using the latest Safari version?

**Comment by gingerbeardman** [comment] 2019-08-04 18:42
This is a little better, the menu is more consistent.

But the search opens in about 1 in 4 clicks of context menu. Or less.

**Comment by gingerbeardman** [comment] 2019-08-04 18:51
Test URL: http://sekaiyugi.com/games/hanafuda-1.html

If I re-enable the extension then it works... for a while.

Video: https://imgur.com/a/gF7PAdT

Latest Safari, and Safari TP.

**Comment by gingerbeardman** [comment] 2019-08-04 18:52
I have (since the video) turned off all extensions other than this one, and the problem still occurs (that is, sometimes) and renabling the extension fixes it temporarily.

**Comment by yimingliu** [comment] 2019-08-04 18:59
That is...odd.  I can't reproduce this on my laptop.  The debug log suggests that it is finding the right URL, but somehow it doesn't open in the new tab.  So the fault would be in the extension itself and not the injected script.

A temporary fix by turning it on-and-off is also weird.  All that is doing, as far as I know, is starting a new process for the extension.  It's almost as if the old extension process just stopped responding to communication from Safari.

I'll try to reproduce this on another machine.

**Comment by yimingliu** [comment] 2019-08-04 19:51
Took a stab at changing up the interprocess communication part.  See if test version 5 works for you.  

I still can't reproduce the issue, but on Safari Tech Preview I can see a bunch of warnings in the log that weren't there before, suggesting that there is some underlying change in Safari that may or may not be related.

EDIT: Please completely delete the previous version. Also, in Activity Monitor, if you see any stray "ReverseImageSearch" processes lingering around, kill those.

**Comment by gingerbeardman** [comment] 2019-08-04 22:34
That seems to have worked! Thank you.

**Comment by gingerbeardman** [comment] 2019-08-05 00:40
Will leave this open until a day or so of testing.

**Comment by differenceclouds** [comment] 2019-11-09 20:27
Guessing this is toast for safari 13?

**Comment by gingerbeardman** [comment] 2019-11-09 21:00
@differenceclouds see here: https://github.com/yimingliu/reverse-image-search-safari/issues/3

it can be made to work, but requires "just right" build process and signing.

it would be nice to get an official release on the Mac App Store.

**Comment by yimingliu** [comment] 2019-11-09 22:05
> Guessing this is toast for safari 13?

Is there something wrong?  I'm using Safari 13.0.3 on Mojave with this extension.

**Comment by differenceclouds** [comment] 2019-11-09 22:22
No, sorry, it works fine! I think I was mistaken because I couldn't find the .app file. Just an oversight on my part! If I may suggest adding Yandex image search, it's the best there is at the moment.

**Comment by differenceclouds** [comment] 2019-11-09 22:26
I got myself in a bit of a state after Safari 13 was released because a ton of extensions stopped working, including a similar extension (that I mistook this one for) that had a few different search engines. Anyway, I'm happy this works.

**Comment by gingerbeardman** [comment] 2019-11-09 22:27
That's a good point, I already modified my own install to add some other image searches I use myself.

Maybe the container app could list them all and allow the user to activate only the ones they want?

**Comment by yimingliu** [comment] 2019-11-09 22:37
> That's a good point, I already modified my own install to add some other image searches I use myself.

I'm happy to add new ones.  If you have specific search engines you want included (I know you're having issues compiling this project), feel free to open an issue.  I can't promise it'll be done quickly, but I will eventually work through these things.

> Maybe the container app could list them all and allow the user to activate only the ones they want?

A good point.  Wasn't much point with 2 sources, but if I were to add, like, 10 of them, then I personally would want to turn off the ones I don't use.

Is this the original issue raised in the ticket resolved?  If so, I'll close this and you can open new ones for new problems.

**Comment by gingerbeardman** [comment] 2019-11-09 22:45
Yes, I'll close.

**Closed as completed** 2019-11-09 22:45 UTC
